### PR TITLE
Corrects the scripts issue with npm/pnpm/yarn

### LINKED ISSUE #39: pnpm run adds quotes in fish shell
Any idea why this would be happening?

image

I've been trying to port it to NixOS, and it's working great for other commands.  My setup is:

```sh
show_media_bias  main @ 729bc98 ⩮✘∽⋄ ❄️ devenv-shell❯  cat (argc-completions-folder)/argc.fish
set -gx ARGC_COMPLETIONS_ROOT "/nix/store/z1kppvmc48kv1aghrz7p945mnf158cqq-argc-completions-2023-12-29"
set -gx ARGC_COMPLETIONS_PATH "$ARGC_COMPLETIONS_ROOT/completions"
fish_add_path "$ARGC_COMPLETIONS_ROOT/bin"
# To add a subset of completions only, change next line e.g. set argc_scripts cargo git
set argc_scripts (ls -1 "$ARGC_COMPLETIONS_ROOT/completions" | sed -n 's/\.sh$//p')
argc --argc-completions fish $argc_scripts | source

show_media_bias  main @ 729bc98 ⩮✘∽⋄ ❄️ devenv-shell❯  argc --argc-completions fish pnpm
function _argc_completer
    set -l args (commandline -o)
    set -l cur (commandline -t)
    if [ ! "$cur" ]
        set -a args ''
    end

    argc --argc-compgen fish "" $args
end


for cmd in argc pnpm
    complete -x -k -c $cmd -a "(_argc_completer)"
end
```

### PR DESCRIPTION
**Pull request by drmikecrowe**
Fixes #39

### CODE REVIEW

**Comment by sigoden** [comment]
This won't fix anything.
image

**Comment by drmikecrowe** [comment]
Ah, we're narrowing it down:

image

**Comment by sigoden** [comment]
```
$ cd argc-completions
$ argc version
argc-completions ce6e212
argc 1.14.0
yq (https://github.com/mikefarah/yq/) version v4.40.4
GNU Awk 5.2.2, API 3.2, PMA Avon 8-g1
sed (GNU sed) 4.8
Linux nix 5.15.0-56-generic #62-Ubuntu SMP Tue Nov 22 19:54:14 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```
what's your yq version?

**Comment by drmikecrowe** [comment]
yep, old version.  Not sure why NixOS unstable is still at v3 and not v4 -- I'm working on an upgrade.

**Comment by sigoden** [comment]
argc-completions require [yq >= 4.25.1](https://github.com/sigoden/argc-completions/blob/ce6e212e09fc551e6ed1c784353bd748c6d0733d/scripts/download-tools.sh#L9)

nix has [yq-go v4.40.3](https://github.com/NixOS/nixpkgs/blob/fe0309c1425729e6985fc120d497743084647137/pkgs/development/tools/yq-go/default.nix#L5)

**Pull request closed without merging**
